import uuid
import os
from app.database import SessionLocal, engine
from app import models

# Ensure tables are created
models.Base.metadata.drop_all(bind=engine)
models.Base.metadata.create_all(bind=engine)

def seed_db():
    db = SessionLocal()

    tools_data = [
        # Productivity
        {"name": "ChatGPT", "slug": "chatgpt", "short_description": "Advanced conversational AI by OpenAI.", "description": "ChatGPT is an AI language model developed by OpenAI, capable of generating human-like text based on context and past conversations.", "website_url": "https://chat.openai.com", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.9},
        {"name": "Notion AI", "slug": "notion-ai", "short_description": "AI-powered workspace and note-taking.", "description": "Notion AI helps you write, edit, summarize, and brainstorm right inside your Notion workspace.", "website_url": "https://www.notion.so/product/ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.7},
        {"name": "Claude", "slug": "claude", "short_description": "Next-generation AI assistant.", "description": "Claude is a highly capable AI assistant created by Anthropic, focused on safety and helpfulness.", "website_url": "https://claude.ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.8},
        {"name": "Grammarly", "slug": "grammarly", "short_description": "AI writing assistant.", "description": "Grammarly uses AI to improve your writing, checking for grammar, tone, and clarity.", "website_url": "https://www.grammarly.com", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.8},
        {"name": "Otter.ai", "slug": "otter-ai", "short_description": "AI meeting assistant and transcription.", "description": "Otter.ai records meetings, takes notes in real time, and generates an automated summary.", "website_url": "https://otter.ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.6},
        {"name": "Fireflies.ai", "slug": "fireflies-ai", "short_description": "Automate your meeting notes.", "description": "Fireflies.ai helps your team record, transcribe, search, and analyze voice conversations.", "website_url": "https://fireflies.ai", "pricing_model": "Paid", "category": "Productivity", "user_rating": 4.5},
        {"name": "Mem", "slug": "mem", "short_description": "The AI-powered workspace.", "description": "Mem organizes your team's work effortlessly using AI.", "website_url": "https://mem.ai", "pricing_model": "Paid", "category": "Productivity", "user_rating": 4.4},
        {"name": "Perplexity", "slug": "perplexity", "short_description": "AI-powered search engine.", "description": "Perplexity is a conversational search engine that gives you direct answers with cited sources.", "website_url": "https://www.perplexity.ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.9},
        {"name": "Gemini", "slug": "gemini", "short_description": "Google's most capable AI model.", "description": "Gemini is Google's multimodal AI, designed for high reasoning and coding capabilities.", "website_url": "https://gemini.google.com", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.7},
        {"name": "Poe", "slug": "poe", "short_description": "Access multiple AI models.", "description": "Poe lets you ask questions, get instant answers, and have back-and-forth conversations with several AI models.", "website_url": "https://poe.com", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.6},
        {"name": "ClickUp Brain", "slug": "clickup-brain", "short_description": "AI-powered assistant inside ClickUp.", "description": "ClickUp Brain connects your tasks, docs, people, and company knowledge with AI to answer questions, write, and automate workflows.", "website_url": "https://clickup.com/features/ai", "pricing_model": "Paid", "category": "Productivity", "user_rating": 4.7},
        {"name": "Coda AI", "slug": "coda-ai", "short_description": "Bring AI to your collaborative docs.", "description": "Coda AI helps you summarize text, autofill tables, draft content, and find information across your docs.", "website_url": "https://coda.io/product/ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.6},
        {"name": "Saner.ai", "slug": "saner-ai", "short_description": "Personal AI workspace for thinking.", "description": "Saner.ai helps you capture notes, recall information quickly, and brainstorm with built-in AI assistants.", "website_url": "https://saner.ai", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.5},
        
        # Marketing
        {"name": "Jasper", "slug": "jasper", "short_description": "AI copywriter for marketing teams.", "description": "Jasper is an AI copywriter and content generator that helps you overcome writer's block to create original, high-converting content quickly.", "website_url": "https://www.jasper.ai", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.6},
        {"name": "Copy.ai", "slug": "copy-ai", "short_description": "Write better marketing copy faster.", "description": "Copy.ai is an AI-powered copywriter that generates high-quality copy for your business.", "website_url": "https://www.copy.ai", "pricing_model": "Freemium", "category": "Marketing", "user_rating": 4.5},
        {"name": "Synthesia", "slug": "synthesia", "short_description": "AI video generation platform.", "description": "Synthesia is the #1 AI video creation platform. Thousands of companies use it to create videos in 120 languages, saving up to 80% of their time and budget.", "website_url": "https://www.synthesia.io", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.7},
        {"name": "Lavender", "slug": "lavender", "short_description": "AI email coach.", "description": "Lavender is an AI email assistant that helps you write better, more effective sales emails.", "website_url": "https://www.lavender.ai", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.8},
        {"name": "Gong", "slug": "gong", "short_description": "Revenue Intelligence platform.", "description": "Gong captures customer interactions across phone, web conferencing, and email, understands what was said, and delivers insights to win more deals.", "website_url": "https://www.gong.io", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.8},
        {"name": "Anyword", "slug": "anyword", "short_description": "Data-driven AI copywriting.", "description": "Anyword is an AI copywriting platform that uses predictive performance scores to help you choose the best copy.", "website_url": "https://anyword.com", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.4},
        {"name": "Surfer SEO", "slug": "surfer-seo", "short_description": "AI-powered SEO tool.", "description": "Surfer is a Content Intelligence tool that merges content strategy, creation, and optimization into one smooth process.", "website_url": "https://surferseo.com", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.7},
        {"name": "Feathery", "slug": "feathery", "short_description": "AI form builder for high-converting forms.", "description": "Feathery uses AI to build complex, customizable forms, questionnaires, and onboarding flows.", "website_url": "https://www.feathery.io", "pricing_model": "Freemium", "category": "Marketing", "user_rating": 4.6},
        {"name": "AdCreative.ai", "slug": "adcreative-ai", "short_description": "AI-generated ad creatives and banners.", "description": "AdCreative.ai generates conversion-focused ad creatives, banners, and social media posts using artificial intelligence.", "website_url": "https://www.adcreative.ai", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.7},
        {"name": "Brandmark", "slug": "brandmark", "short_description": "AI logo and brand identity generator.", "description": "Brandmark builds professional logo designs and complete brand identities instantly using generative AI.", "website_url": "https://brandmark.io", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.5},
        
        # Design & Video
        {"name": "Midjourney", "slug": "midjourney", "short_description": "High-quality AI image generation.", "description": "Midjourney generates images from natural language descriptions, known as prompts, similar to OpenAI's DALL-E and Stable Diffusion.", "website_url": "https://www.midjourney.com", "pricing_model": "Paid", "category": "Design", "user_rating": 4.8},
        {"name": "Descript", "slug": "descript", "short_description": "All-in-one video and audio editing.", "description": "Descript is a new kind of video editor that's as easy as a doc. It includes transcription, a screen recorder, publishing, full multitrack editing, and some mind-bendingly useful AI tools.", "website_url": "https://www.descript.com", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.8},
        {"name": "Beautiful.ai", "slug": "beautiful-ai", "short_description": "AI presentation maker.", "description": "Beautiful.ai is presentation software that applies the rules of great design in real-time.", "website_url": "https://www.beautiful.ai", "pricing_model": "Paid", "category": "Design", "user_rating": 4.6},
        {"name": "Tome", "slug": "tome", "short_description": "AI storytelling format.", "description": "Tome uses AI to help you create presentations, one-pagers, and stories in seconds.", "website_url": "https://tome.app", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.5},
        {"name": "Runway", "slug": "runway", "short_description": "AI magic tools for creators.", "description": "Runway is an applied AI research company shaping the next era of art, entertainment and human creativity.", "website_url": "https://runwayml.com", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.7},
        {"name": "Canva Magic Studio", "slug": "canva-magic-studio", "short_description": "AI design tools in Canva.", "description": "Canva's Magic Studio brings the power of AI to your designs, making it easier than ever to create stunning graphics.", "website_url": "https://www.canva.com", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.8},
        {"name": "ElevenLabs", "slug": "elevenlabs", "short_description": "AI voice generator.", "description": "ElevenLabs is the most realistic text-to-speech software, allowing you to generate lifelike audio in any voice.", "website_url": "https://elevenlabs.io", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.9},
        {"name": "Murf.ai", "slug": "murf-ai", "short_description": "AI voice generator.", "description": "Murf offers high-quality AI voices for your videos, podcasts, and presentations.", "website_url": "https://murf.ai", "pricing_model": "Paid", "category": "Design", "user_rating": 4.5},
        {"name": "DALL-E 3", "slug": "dall-e", "short_description": "AI image generation by OpenAI.", "description": "DALL-E 3 understands significantly more nuance and detail than previous systems, allowing you to easily translate your ideas into exceptionally accurate images.", "website_url": "https://openai.com/dall-e-3", "pricing_model": "Paid", "category": "Design", "user_rating": 4.7},
        {"name": "Stable Diffusion", "slug": "stable-diffusion", "short_description": "Open-source image generation.", "description": "Stable Diffusion is a latent text-to-image diffusion model capable of generating photo-realistic images given any text input.", "website_url": "https://stability.ai", "pricing_model": "Free", "category": "Design", "user_rating": 4.6},
        {"name": "Luma Dream Machine", "slug": "luma-dream-machine", "short_description": "AI video generation.", "description": "Luma Dream Machine is an AI model that makes high quality, realistic videos fast from text and images.", "website_url": "https://lumalabs.ai", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.7},
        {"name": "Suno", "slug": "suno", "short_description": "AI music generation.", "description": "Suno is building a future where anyone can make great music, using AI.", "website_url": "https://suno.com", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.8},
        {"name": "Udio", "slug": "udio", "short_description": "AI music creation platform.", "description": "Udio is an AI model that generates highly realistic music from text prompts.", "website_url": "https://udio.com", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.7},
        {"name": "Veed.io", "slug": "veed-io", "short_description": "AI-powered online video editor.", "description": "Veed.io provides AI-driven video editing features including auto-subtitles, voice translation, and smart background removal.", "website_url": "https://www.veed.io", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.7},
        {"name": "InVideo AI", "slug": "invideo-ai", "short_description": "Generate videos from text prompts.", "description": "InVideo AI simplifies video creation by generating high-quality scripts, voiceovers, and videos from text prompts.", "website_url": "https://invideo.io", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.8},
        {"name": "Galileo AI", "slug": "galileo-ai", "short_description": "AI-powered UI design generator.", "description": "Galileo AI generates editable UI designs from natural language prompts, instantly speeding up product design.", "website_url": "https://www.usegalileo.ai", "pricing_model": "Freemium", "category": "Design", "user_rating": 4.8},
        
        # Development
        {"name": "GitHub Copilot", "slug": "github-copilot", "short_description": "Your AI pair programmer.", "description": "GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time, right from your editor.", "website_url": "https://github.com/features/copilot", "pricing_model": "Paid", "category": "Development", "user_rating": 4.8},
        {"name": "Cursor", "slug": "cursor", "short_description": "The AI Code Editor.", "description": "Cursor is a fork of VS Code tailored for AI programming.", "website_url": "https://cursor.sh", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.9},
        {"name": "Baseten", "slug": "baseten", "short_description": "Deploy AI models fast.", "description": "Baseten provides infrastructure for deploying ML models in production.", "website_url": "https://www.baseten.co", "pricing_model": "Paid", "category": "Development", "user_rating": 4.5},
        {"name": "Replicate", "slug": "replicate", "short_description": "Run AI models with an API.", "description": "Replicate makes it easy to run machine learning models in the cloud.", "website_url": "https://replicate.com", "pricing_model": "Paid", "category": "Development", "user_rating": 4.7},
        {"name": "Pinecone", "slug": "pinecone", "short_description": "Vector database for AI.", "description": "Pinecone makes it easy to provide long-term memory for high-performance AI applications.", "website_url": "https://www.pinecone.io", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.8},
        {"name": "LangChain", "slug": "langchain", "short_description": "Framework for LLM apps.", "description": "LangChain is a framework for developing applications powered by language models.", "website_url": "https://langchain.com", "pricing_model": "Free", "category": "Development", "user_rating": 4.7},
        {"name": "Scale AI", "slug": "scale-ai", "short_description": "Data platform for AI.", "description": "Scale accelerates the development of AI applications by helping machine learning teams generate high-quality ground truth data.", "website_url": "https://scale.com", "pricing_model": "Paid", "category": "Development", "user_rating": 4.6},
        {"name": "Hugging Face", "slug": "hugging-face", "short_description": "The AI community building the future.", "description": "Hugging Face is the collaboration platform for the machine learning community.", "website_url": "https://huggingface.co", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.9},
        {"name": "V0", "slug": "v0-by-vercel", "short_description": "AI UI generator by Vercel.", "description": "v0 generates production-ready React code with Tailwind CSS and shadcn/ui from simple text prompts.", "website_url": "https://v0.dev", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.9},
        {"name": "Tabnine", "slug": "tabnine", "short_description": "AI assistant for software developers.", "description": "Tabnine provides context-aware code completions and chat assistant features directly in your IDE.", "website_url": "https://www.tabnine.com", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.6},
        {"name": "LangFuse", "slug": "langfuse", "short_description": "Open source LLM engineering platform.", "description": "Langfuse provides open-source analytics, tracing, evaluations, and prompt management for LLM applications.", "website_url": "https://langfuse.com", "pricing_model": "Freemium", "category": "Development", "user_rating": 4.8},
        
        # Automation
        {"name": "Zapier Central", "slug": "zapier-central", "short_description": "AI automation hub.", "description": "Zapier Central lets you teach AI bots to work across 6,000+ apps.", "website_url": "https://zapier.com/central", "pricing_model": "Paid", "category": "Automation", "user_rating": 4.6},
        {"name": "Make", "slug": "make", "short_description": "Visual automation platform.", "description": "Make allows you to visually create, build, and automate workflows without coding.", "website_url": "https://www.make.com", "pricing_model": "Freemium", "category": "Automation", "user_rating": 4.8},
        {"name": "DataRobot", "slug": "datarobot", "short_description": "Value-driven AI platform.", "description": "DataRobot accelerates your AI journey from data to value.", "website_url": "https://www.datarobot.com", "pricing_model": "Paid", "category": "Automation", "user_rating": 4.5},
        {"name": "H2O.ai", "slug": "h2o-ai", "short_description": "Open source machine learning.", "description": "H2O.ai is the open source leader in AI and automatic machine learning.", "website_url": "https://h2o.ai", "pricing_model": "Freemium", "category": "Automation", "user_rating": 4.6},
        {"name": "n8n", "slug": "n8n", "short_description": "Fair-code workflow automation tool.", "description": "n8n is an extendable workflow automation tool that lets you connect anything to everything with native AI capabilities.", "website_url": "https://n8n.io", "pricing_model": "Freemium", "category": "Automation", "user_rating": 4.8},
        {"name": "Bardeen", "slug": "bardeen", "short_description": "AI-powered browser automation.", "description": "Bardeen automates repetitive tasks directly from your browser, scraping web pages and integrating with apps.", "website_url": "https://www.bardeen.ai", "pricing_model": "Freemium", "category": "Automation", "user_rating": 4.7},
        {"name": "LlamaIndex", "slug": "llamaindex", "short_description": "Data framework for LLM applications.", "description": "LlamaIndex provides data ingestion, indexing, and querying tools to connect custom data sources to LLMs.", "website_url": "https://www.llamaindex.ai", "pricing_model": "Free", "category": "Automation", "user_rating": 4.8},
        
        # Finance & HR
        {"name": "AlphaSense", "slug": "alphasense", "short_description": "Market intelligence and search platform.", "description": "AlphaSense helps you uncover insights from millions of financial documents.", "website_url": "https://www.alpha-sense.com", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.5},
        {"name": "Kensho", "slug": "kensho", "short_description": "AI for finance.", "description": "Kensho brings machine learning, analytics, and data-driven insights to the financial sector.", "website_url": "https://kensho.com", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.4},
        {"name": "Booke.ai", "slug": "booke-ai", "short_description": "AI bookkeeping and reconciliation.", "description": "Booke.ai automates transactions reconciliation, flags discrepancies, and simplifies client communication for accountants.", "website_url": "https://booke.ai", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.6},
        {"name": "Vic.ai", "slug": "vic-ai", "short_description": "AI enterprise invoice processing.", "description": "Vic.ai uses autonomous artificial intelligence to automate accounts payable, invoice processing, and approvals.", "website_url": "https://www.vic.ai", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.5},
        {"name": "Trullion", "slug": "trullion", "short_description": "AI-powered accounting and audit platform.", "description": "Trullion uses AI to automate lease accounting, revenue recognition, and audit workflows for finance teams.", "website_url": "https://trullion.com", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.7},
        {"name": "Paradox", "slug": "paradox", "short_description": "Conversational recruiting software.", "description": "Paradox uses an AI assistant named Olivia to automate administrative hiring tasks.", "website_url": "https://www.paradox.ai", "pricing_model": "Paid", "category": "HR", "user_rating": 4.6},
        {"name": "Eightfold.ai", "slug": "eightfold-ai", "short_description": "AI for talent acquisition.", "description": "Eightfold delivers a Talent Intelligence Platform, powered by AI.", "website_url": "https://eightfold.ai", "pricing_model": "Paid", "category": "HR", "user_rating": 4.7},
        {"name": "SeekOut", "slug": "seekout", "short_description": "Talent intelligence platform.", "description": "SeekOut provides an AI-powered talent search engine for recruiters.", "website_url": "https://seekout.com", "pricing_model": "Paid", "category": "HR", "user_rating": 4.6},
        {"name": "Textio", "slug": "textio", "short_description": "Augmented writing for HR.", "description": "Textio brings advanced language insights into your hiring and employer brand content.", "website_url": "https://textio.com", "pricing_model": "Paid", "category": "HR", "user_rating": 4.5},
        {"name": "Beamery", "slug": "beamery", "short_description": "Talent lifecycle management.", "description": "Beamery uses AI to help you attract, engage, and retain top talent.", "website_url": "https://beamery.com", "pricing_model": "Paid", "category": "HR", "user_rating": 4.6},
        {"name": "HireVue", "slug": "hirevue", "short_description": "Video interviewing software.", "description": "HireVue provides video interviews and assessments powered by AI.", "website_url": "https://www.hirevue.com", "pricing_model": "Paid", "category": "HR", "user_rating": 4.4},
        {"name": "Attract", "slug": "attract", "short_description": "AI-powered search engine for recruiters.", "description": "Attract helps recruiting teams discover, engage, and hire talent through personalized AI search and outreach.", "website_url": "https://www.attract.ai", "pricing_model": "Paid", "category": "HR", "user_rating": 4.6},
        {"name": "Fetcher", "slug": "fetcher", "short_description": "Automated recruiting and sourcing pipeline.", "description": "Fetcher combines AI with human curation to source candidates and schedule automated email campaigns.", "website_url": "https://www.fetcher.ai", "pricing_model": "Paid", "category": "HR", "user_rating": 4.5},
        {"name": "Juicebox", "slug": "juicebox", "short_description": "AI-powered talent discovery.", "description": "Juicebox uses AI search models to find hidden talent pools, assess skills, and optimize the recruitment funnel.", "website_url": "https://www.juicebox.work", "pricing_model": "Freemium", "category": "HR", "user_rating": 4.6},
        
        # Custom Unique Tools
        {"name": "SiloPulse", "slug": "silopulse", "short_description": "Organizational silo and department collaboration friction analyzer.", "description": "SiloPulse analyzes anonymized metadata from team communication networks to map connectivity, flag isolated departments, and spot workflow bottlenecks before they impact performance.", "website_url": "https://silopulse.ai-custom-tools.org", "pricing_model": "Freemium", "category": "HR", "user_rating": 4.9},
        {"name": "ProphetLedger", "slug": "prophetledger", "short_description": "AI opportunity cost and business decision inaction simulator.", "description": "ProphetLedger simulates alternative strategic routes for your business, calculating the financial cost and missed revenue of delayed decisions or bypassed project opportunities.", "website_url": "https://prophetledger.ai-custom-tools.org", "pricing_model": "Paid", "category": "Finance", "user_rating": 4.8},
        {"name": "EchoAudit", "slug": "echoaudit", "short_description": "Executive echo-chamber and board decision bias auditing system.", "description": "EchoAudit processes meeting notes and board transcript summaries to identify cognitive bias, decision groupthink, and lack of diverse perspectives, proposing structural devil's advocate reviews.", "website_url": "https://echoaudit.ai-custom-tools.org", "pricing_model": "Freemium", "category": "Productivity", "user_rating": 4.7},
        {"name": "VibeContract", "slug": "vibecontract", "short_description": "Brand-trust and subconscious language alignment auditor for contracts.", "description": "VibeContract analyzes legal terms of service and customer agreements, translating heavy legalese into user-friendly summaries and scoring the emotional brand trust alignment.", "website_url": "https://vibecontract.ai-custom-tools.org", "pricing_model": "Paid", "category": "Marketing", "user_rating": 4.9},
        {"name": "CarbonIdle", "slug": "carbonidle", "short_description": "Digital carbon footprint tracker and cloud resource waste automator.", "description": "CarbonIdle monitors cloud architecture deployments, identifying idle instances, obsolete cache layers, and inefficient APIs, offering single-click automated optimization to save costs and CO2.", "website_url": "https://carbonidle.ai-custom-tools.org", "pricing_model": "Free", "category": "Automation", "user_rating": 4.6},
        {"name": "MemeScale", "slug": "memescale", "short_description": "Pop-culture viral trend translator for enterprise B2B marketing.", "description": "MemeScale maps trending TikTok, Reddit, and Twitter pop-culture references into compliant, brand-safe, and highly engaging professional B2B LinkedIn updates to accelerate growth.", "website_url": "https://memescale.ai-custom-tools.org", "pricing_model": "Freemium", "category": "Marketing", "user_rating": 4.8},
        {"name": "ShapeShifter API", "slug": "shapeshifter-api", "short_description": "Dynamic outbound response shape-shifter for legacy API endpoints.", "description": "ShapeShifter API automatically transforms data schemas on-the-fly to conform to legacy or undocumented client systems, accelerating B2B software integrations.", "website_url": "https://shapeshifter.ai-custom-tools.org", "pricing_model": "Paid", "category": "Development", "user_rating": 4.8},
        {"name": "ResilioStress", "slug": "resiliostress", "short_description": "Operational alert fatigue dampener and human-centric circadian scheduler.", "description": "ResilioStress detects alert fatigue across developer and operations channels, automatically grouping and rescheduling alerts around human sleep and focus cycles.", "website_url": "https://resiliostress.ai-custom-tools.org", "pricing_model": "Paid", "category": "HR", "user_rating": 4.7}
    ]

    for data in tools_data:
        tool = models.Tool(**data)
        db.add(tool)

    db.commit()
    print(f"Successfully seeded {len(tools_data)} tools.")
    db.close()

if __name__ == "__main__":
    seed_db()
